### ISSUE TITLE
Error computing planning mask

### ISSUE THREAD

**Issue by sitiny** [ProteusMRIgHIFU/BabelBrain#8]
Hi Sam, 

I ran into this error while computing the planning mask. It's only on my computer (I managed to get it to work with identical files on a different iMac). My computer is a MacBook Pro (Intel 2 GHz Quad-Core Intel Core i5, 16GB RAM).

Would you know what this is and how to fix it please?

Thanks,
Siti

The error comes after Code block 'skin voxelization' and the error is as follows: 

Code block 'skin voxelization' took: 1.31554 s
--Babel-Brain-Low-Error
Traceback (most recent call last):
  File "/Users/sitiyaakub/Documents/Software/BabelBrain/BabelBrain/CalculateMaskProcess.py", line 73, in CalculateMaskProcess
    DataPreps.GetSkullMaskFromSimbNIBSSTL(**kargs)
  File "/Users/sitiyaakub/Documents/Software/BabelBrain/BabelBrain/BabelDatasetPreps.py", line 437, in GetSkullMaskFromSimbNIBSSTL
    skin_grid = VoxelizeFilter(skin_mesh,targetResolution=SpatialStep*0.75,GPUBackend=VoxelizeCOMPUTING_BACKEND)
  File "/Users/sitiyaakub/Documents/Software/BabelBrain/BabelBrain/GPUVoxelize/Voxelize.py", line 558, in Voxelize
    Points_dev=ctx.buffer(Points_part.nbytes)
metalcompute.error: Could not make buffer

Could not make buffer
****************************************
***** Error in execution.
****************************************

**Comment by spichardo** [comment]
Hi sitiny,

The issue is that you are using an Intel-based Macbook Pro system. Those devices have some simple GPUs that are not adequate for GPU calculations. As you can see in the error "metalcompute.error: Could not make buffer", the GPU may not have enough memory for the processing. Intel-based systems work great if you have a dedicate AMD GPU (either internally or externally via Thunderbolt). I used BabelBrain often with an Intel-based Mac with an external AMD 6800 PRO.

Was the other Mac based on the newer M1 or M2 processors? Those processors have their GPU sharing the whole memory, allowing running these memory-intense calculations.  I may have to be much more specific in the instruction to be sure people are aware of the limitations when using Intel-based  Mac systems. I do not have any other suggestion other than switching to a newer Mac system based on the M1/M2 processors or getting an external GPU to run simulations.

**Comment by spichardo** [comment]
Added more details on requirements for Intel-based Mac systems on Readme (ecd849d4460b4cccd58a2a94e4668664c59d8c5f) and in documentation (beb5d63baff47f2a66fe5625283348aed82df94e)
